### ISSUE TITLE
pattern voor verblijfstitel_tabel.code is niet juist

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#230]
attribuut "code" in Verblijfstitel_tabel is als volgt gedefinieerd:

```
        code:
          type: "string"
          title: "Verblijfstitel numeriek"
          description: "Het nummer van de verblijfstitel alle natuurlijk getallen\
            \ met voorloopnullen (inclusief 00)"
          pattern: "^[0-9]$"
          maxLength: 2
          example: "09"
```

De definitie van pattern staat nu maar 1 cijfer toe, terwijl maxLength =2 en de voorloopnul gebruikt moet worden (zie description en example).

Dus pattern moet zijn "^[0-9]{2}$"

Ook blijkt de description soms verwarring te geven door de tekst "inclusief 00". Dit kan (blijkt) zo gelezen worden dat er altijd 2 nullen voor de verblijfstitel moeten worden toegevoegd. Bijvoorbeeld 09 wordt 0009.

Ik stel voor de tekst " (inclusief 00)" uit de description weg te laten.
