### ISSUE TITLE
Zijn sommige elementen in het antwoord op een vraag verplicht?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#3]
In de informatiemodellen (zoals RSGB) zijn sommige attributen verplicht. Hier betekent dit dat dit attribuut er altijd moet zijn. Bijvoorbeeld een ingeschreven natuurlijk persoon heeft altijd een naam.

Betekent dit dat deze attributen ook verplicht moeten zijn in de response op GET /ingeschrevennatuurlijkpersonen?

Ratio voor het verplichten van elementen: de consumer kan er zeker van zijn dat het element bestaat en een waarde heeft
Ratio voor niet verplichten: we moeten dan zeker zijn dat er in de registratie ook daadwerkelijk altijd een waarde is. Bericht niet onnodig restricten

**Comment by melsk-r** [comment]
Volgens mij kun je niet stellen dat een gegeven dat in een informatiemodel verplicht is ook altijd uitgevraagd moet worden. De verplichtstelling van een attribuut in een informatiemodel betekent wat anders dan de verplichtstelling van een attribuut in het berichtmodel.
Ik denk wel dat de verplichtstelling in een uitwisselingsgegevensmodel hetzelfde betekent als de verplichtstelling  in een berichtmodel.

**Comment by JohanBoer** [comment]
Technisch gezien betekent het verplicht stellen van een element of een gegevensgroep dat het element of de gegevensgroep voor moet komen in het antwoord bericht. Dat element kan dan altijd nog een null-waarde hebben. Het verplicht opnemen van elementen conform het informatiemodel (of uitwisselingsmodel) zal dus niet leiden tot foute of ontbrekende resultaten. Zie ook #45

**Comment by fsamwel** [comment]
verwerkt in [beslissing](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md#de-response-heeft-geen-verplichte-properties)

**Comment by fsamwel** [comment]
is nog niet (overal) doorgevoerd in de API specificaties. bijvoorbeeld:
```
Overlijden:
      type: "object"
      description: "Gegevens over het overlijden van de ingeschreven natuurlijk persoon.\
        \ Zie verder de toelichting in de GBA."
      required:
      - "datumOverlijden"
      - "plaatsOverlijden"
      - "landOverlijden"
```
