### ISSUE TITLE
Wat is de functie van de 1-letterige code in de enumerations

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#665]
@JohanBoer @MelvLee @fsamwel 
Wat is eigenlijk in de enumerations de functie van de 1-letterige codes (bijv. 'E') in de descriptions van de enumeratiewaarden? 
Bijv.:

```yaml
    Naamgebruik_enum:
      type: string
      description: |-
        De voorgedefinieerde waarden van naamgebruik volgens de centrale voorzieningen.
        * `eigen` - E
        * `eigen_partner` - N
        * `partner` - P
        * `partner_eigen` - V
      enum:
      - eigen
      - eigen_partner
      - partner
      - partner_eigen
```
Als de enumeratiewaarde zelf een 1-letterige code was dan zou ik me wat voor kunnen stellen bij een omschrijving. De 1-letterige code voegt volgens mij hier niet zo veel toe.
