### ISSUE TITLE
Reguliere expressie burgerservicenummer niet correct

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#830]
Het viel mij op dat we bij burgerservicenummer het volgende hebben staan:
Raadplegen:
```
      - name: burgerservicenummer
        in: path
        description: |
          Uniek persoonsnummer
        required: true
        style: simple
        explode: false
        schema:
          maxLength: 9
          minLength: 9
          pattern: ^[0-9]*$
          type: string
          example: "555555021"
```
Zoeken:
```
      - name: burgerservicenummer
        in: query
        description: |
          Uniek persoonsnummer.
        required: false
        style: form
        explode: false
        schema:
          type: array
          items:
            maxLength: 9
            minLength: 9
            pattern: ^[0-9]*$
            type: string
        example: 999993653,999991723,999995078
```
waar bij beiden een pattern wordt gehanteerd van ^[0-9]*$. Dit houdt in dat zolang de value tussen de 0 t/m 9 als karakter heeft dat het niet uitmaakt of die nou 5 karakters heeft of 200. Ik zou eerlijk gezegd verwachten dat we het krijgen ^[0-9]{9}$ namelijk een exacte quantifier op 9 zoals bsn ook is. We hebben inderdaad wel een controle op min en max lengte (wat overbodig is met een pattern) maar dat betekent niet dat de pattern zo maar foutief mag zijn.

Dit zal wellicht een breaking change inhouden, maar ik vraag me af waarom dit überhaupt nooit is aangekaart.
