### ISSUE TITLE
pattern voor parameter straat moet punt toestaan

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#983]
```
    StraatFilter:
      pattern: ^[a-zA-Z0-9À-ž \-\']{1,80}$|^[a-zA-Z0-9À-ž \-\']{7,79}\*{1}$|^\*{1}[a-zA-Z0-9À-ž
        \-\']{7,79}$
      type: string
```

Dit staat het niet toe dat gezocht wordt met "." (een punt) in de zoektekst voor parameter 'straat'.

Dit pattern is te beperkend, want een punt kan voorkomen in een openbare ruimtenaam. Bijvoorbeeld "0344300000000857" heeft naam "St.-Jacobsstraat"

Het pattern moet worden gewijzigd in: ```^[a-zA-Z0-9À-ž \-\'\.]{1,80}$|^[a-zA-Z0-9À-ž \-\'\.]{7,79}\*{1}$|^\*{1}[a-zA-Z0-9À-ž \-\'\.]{7,79}$```
